import type { Metadata } from "next";
import { Inter } from "next/font/google";


import "./globals.css";

import Footer from "@/components/Footer";
import Navigation from "@/components/navigation";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body>
    
        <main className="relative overflow-hidden">
        <Navigation/>
          {children}
        <Footer/>
        </main>
        
      </body>
    </html>
  );
}
